# Generated by Django 3.2.13 on 2022-05-21 08:40

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_question_has_multiple_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='uuid',
            field=django_extensions.db.fields.ShortUUIDField(blank=True, editable=False, max_length=6, null=True),
        ),
    ]
