# Generated by Django 3.2.13 on 2022-05-21 10:47

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_quiz_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='uuid',
            field=django_extensions.db.fields.ShortUUIDField(blank=True, editable=False, null=True),
        ),
    ]
